/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.DAOProduto;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.IOException;
import static java.lang.System.exit;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.ModelProduto;

/**
 *
 * @author JuLio
 */
public class TelaProduto extends javax.swing.JFrame {
    
    long cod_barra, ncm;
    int id, qt_estoque,estoque_min, estoque_max;
    String cod, status,nome, descricao,imagem, data;
    float pr_compra, pr_venda,fator;
        
    ModelProduto mproduto = new ModelProduto();
    DAOProduto dproduto = new DAOProduto();
    /**
     * Creates new form TelaProduto
     */
    public TelaProduto() {
        initComponents();
        
        listarProdutos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbimagem = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnlimpar = new javax.swing.JButton();
        btnimprimir = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btncadastrar = new javax.swing.JButton();
        btnsair = new javax.swing.JButton();
        txtnome = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        txtestoque = new javax.swing.JTextField();
        txtdescricao = new javax.swing.JTextField();
        txtestoqueMin = new javax.swing.JTextField();
        txtestoqueMax = new javax.swing.JTextField();
        txtprecoCompra = new javax.swing.JTextField();
        txtprecoVenda = new javax.swing.JTextField();
        txtlucro = new javax.swing.JTextField();
        txtncm = new javax.swing.JTextField();
        txtcodigoBarra = new javax.swing.JTextField();
        txtimagem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbproduto = new javax.swing.JTable();
        txtdata = new javax.swing.JFormattedTextField();
        btnbuscarimagem = new javax.swing.JButton();
        cbopcao = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemsobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Código");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Descrição");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Data de cadastro");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Status");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Estoque mínimo");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Estoque máximo");

        lbimagem.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbimagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Código de barras GTIN/EAN");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Quantidade em estoque");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("NCM");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Fator lucro %");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Preço de venda");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("Preço de compra");

        btnlimpar.setText("Limpar");
        btnlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparActionPerformed(evt);
            }
        });

        btnimprimir.setText("Imprimir");
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });

        btndelete.setText("Apagar");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btncadastrar.setText("Novo");
        btncadastrar.setActionCommand("");
        btncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarActionPerformed(evt);
            }
        });

        btnsair.setText("Sair");
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });

        txtestoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestoqueActionPerformed(evt);
            }
        });

        txtprecoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecoCompraActionPerformed(evt);
            }
        });

        txtlucro.setEditable(false);

        txtimagem.setEditable(false);
        txtimagem.setText("Selecione a imagem");
        txtimagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtimagemMouseClicked(evt);
            }
        });
        txtimagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtimagemActionPerformed(evt);
            }
        });

        tbproduto.setAutoCreateRowSorter(true);
        tbproduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Codigo", "Status", "Nome", "Descrição", "Estoque", "Estoque minimo", "Estoque maximo", "Preço de compra", "Preço de venda", "Codigo de barra", "NCM", "Fator lucro %", "Data Cadastro", "URL Imagem"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbproduto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbproduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbprodutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbproduto);

        try {
            txtdata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdata.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnbuscarimagem.setText("...");
        btnbuscarimagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarimagemActionPerformed(evt);
            }
        });

        cbopcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "I-Inativo", "A-Ativo" }));
        cbopcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbopcaoActionPerformed(evt);
            }
        });

        jMenu1.setText("Mais");

        itemsobre.setText("Sobre");
        itemsobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsobreActionPerformed(evt);
            }
        });
        jMenu1.add(itemsobre);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtdescricao, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtestoque, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel11)
                                                        .addGap(25, 25, 25))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(133, 133, 133)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel4)
                                                        .addGap(38, 38, 38))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(121, 121, 121)
                                                        .addComponent(cbopcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE)))))
                                        .addGap(0, 43, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtncm)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txtestoqueMax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                                    .addComponent(txtprecoVenda))
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel7)))
                                        .addGap(99, 99, 99)
                                        .addComponent(lbimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)))
                                .addGap(68, 68, 68))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(txtprecoCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                        .addComponent(txtestoqueMin)
                                        .addComponent(txtlucro))
                                    .addComponent(txtcodigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnbuscarimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btneditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btncadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btndelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnimprimir, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(btnlimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnsair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(117, 117, 117)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdata, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbopcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtestoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btneditar))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btndelete)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btncadastrar)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtestoqueMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtestoqueMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnlimpar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(btnsair))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtprecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel13)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addComponent(btnimprimir))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtlucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(83, 83, 83)
                                                .addComponent(jLabel10)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtcodigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtprecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtncm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtimagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbuscarimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarActionPerformed
        
        qt_estoque =Integer.parseInt(txtestoque.getText());
        estoque_min = Integer.parseInt(txtestoqueMin.getText());
        estoque_max = Integer.parseInt(txtestoqueMax.getText());
        pr_compra = Float.valueOf(txtprecoCompra.getText());
        pr_venda = Float.valueOf(txtprecoVenda.getText());
        cod_barra = Long.valueOf(txtcodigoBarra.getText());
        ncm = Long.valueOf(txtncm.getText());
        //fator = Float.valueOf(txtlucro.getText());
        
        fator= ((pr_venda-pr_compra)/pr_compra)*100;
        
        
        
        
        mproduto.setCod(txtcodigo.getText());
        //mproduto.setStatus(txtstatus.getText());
        mproduto.setStatus((String) cbopcao.getSelectedItem());
        mproduto.setNome(txtnome.getText());
        mproduto.setDescricao(txtdescricao.getText());
        mproduto.setQtd_estoque(qt_estoque);
        mproduto.setEstoque_minimo(estoque_min);
        mproduto.setEstoque_maximo(estoque_max);
        mproduto.setPreco_compra(pr_compra);
        mproduto.setPreco_venda(pr_venda);
        mproduto.setBar_code(cod_barra);
        mproduto.setNcm(ncm);
        mproduto.setFator(fator);
        mproduto.setData_cadastro(txtdata.getText());
        mproduto.setImagem(txtimagem.getText());
        
        dproduto.salvarProdutoDAO(mproduto);
        
        limpar();
        listarProdutos();
        
    }//GEN-LAST:event_btncadastrarActionPerformed

    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed
        limpar();
        
    }//GEN-LAST:event_btnlimparActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        
        
        qt_estoque =Integer.parseInt(txtestoque.getText());
        estoque_min = Integer.parseInt(txtestoqueMin.getText());
        estoque_max = Integer.parseInt(txtestoqueMax.getText());
        pr_compra = Float.valueOf(txtprecoCompra.getText());
        pr_venda = Float.valueOf(txtprecoVenda.getText());
        cod_barra = Long.valueOf(txtcodigoBarra.getText());
        ncm = Long.valueOf(txtncm.getText());
        //fator = Float.valueOf(txtlucro.getText());
        
        fator= ((pr_venda-pr_compra)/pr_compra)*100;
        
        mproduto.setId(id);
        
        mproduto.setCod(txtcodigo.getText());
        //mproduto.setStatus(txtstatus.getText());
        mproduto.setStatus((String) cbopcao.getSelectedItem());
        mproduto.setNome(txtnome.getText());
        mproduto.setDescricao(txtdescricao.getText());
        mproduto.setQtd_estoque(qt_estoque);
        mproduto.setEstoque_minimo(estoque_min);
        mproduto.setEstoque_maximo(estoque_max);
        mproduto.setPreco_compra(pr_compra);
        mproduto.setPreco_venda(pr_venda);
        mproduto.setBar_code(cod_barra);
        mproduto.setNcm(ncm);
        mproduto.setFator(fator);
        mproduto.setData_cadastro(txtdata.getText());
        mproduto.setImagem(txtimagem.getText());
        
        dproduto.atualizarProdutoDAO(mproduto);
        
        limpar();
        listarProdutos();
        
    }//GEN-LAST:event_btneditarActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        dproduto.excluirProdutoDAO(id);
        listarProdutos();
        limpar();
    }//GEN-LAST:event_btndeleteActionPerformed

    private void tbprodutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbprodutoMouseClicked
        carregarCampos();
    }//GEN-LAST:event_tbprodutoMouseClicked

    private void txtestoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestoqueActionPerformed

    private void txtprecoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecoCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecoCompraActionPerformed

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        MessageFormat head= new MessageFormat("");
        MessageFormat rodape= new MessageFormat("");
        
        try {
            tbproduto.print(JTable.PrintMode.NORMAL, head, rodape);
        } 
        catch (PrinterException ex) {
            Logger.getLogger(TelaProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnimprimirActionPerformed

    private void txtimagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtimagemActionPerformed
        
    }//GEN-LAST:event_txtimagemActionPerformed

    private void txtimagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtimagemMouseClicked
        
               
        
        
        
    }//GEN-LAST:event_txtimagemMouseClicked

    private void btnbuscarimagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarimagemActionPerformed
        JFileChooser chooser = new JFileChooser();
        File f = null;
        try {
            f = new File(new File("filename.txt").getCanonicalPath());
        } 
        catch (IOException ex){
            Logger.getLogger(TelaProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
        chooser.setSelectedFile(f);
        chooser.showOpenDialog(null);
        File curFile = chooser.getSelectedFile();
               
        
        txtimagem.setText(""+curFile.toString());
        
        ImageIcon icon = new ImageIcon(curFile.toString());
        
        lbimagem.setIcon(icon);
    }//GEN-LAST:event_btnbuscarimagemActionPerformed

    private void cbopcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbopcaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbopcaoActionPerformed

    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
        exit(0);
    }//GEN-LAST:event_btnsairActionPerformed

    private void itemsobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemsobreActionPerformed
        Sobre sobre = new Sobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_itemsobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProduto().setVisible(true);
                               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscarimagem;
    private javax.swing.JButton btncadastrar;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JButton btnlimpar;
    private javax.swing.JButton btnsair;
    private javax.swing.JComboBox<String> cbopcao;
    private javax.swing.JMenuItem itemsobre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbimagem;
    private javax.swing.JTable tbproduto;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcodigoBarra;
    private javax.swing.JFormattedTextField txtdata;
    private javax.swing.JTextField txtdescricao;
    private javax.swing.JTextField txtestoque;
    private javax.swing.JTextField txtestoqueMax;
    private javax.swing.JTextField txtestoqueMin;
    private javax.swing.JTextField txtimagem;
    private javax.swing.JTextField txtlucro;
    private javax.swing.JTextField txtncm;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtprecoCompra;
    private javax.swing.JTextField txtprecoVenda;
    // End of variables declaration//GEN-END:variables

    public void limpar(){
    
        txtcodigo.setText("");
        //txtstatus.setText("");
        txtnome.setText("");
        txtdescricao.setText("");
        txtestoque.setText("");
        txtestoqueMin.setText("");
        txtestoqueMax.setText("");
        txtprecoCompra.setText("");
        txtprecoVenda.setText("");
        txtcodigoBarra.setText("");
        txtncm.setText("");
        txtlucro.setText("");
        txtdata.setText("");
        txtimagem.setText("");
        lbimagem.setIcon(null);
        
    
    }
    
    private void listarProdutos(){
    
        try {
            
            DefaultTableModel tbmodelo = (DefaultTableModel) tbproduto.getModel();
            
            tbmodelo.setNumRows(0);
            
            ArrayList<ModelProduto> lista = dproduto.getListaProdutoDAO();
            
            for(int i=0; i<lista.size(); i++){
                tbmodelo.addRow(new Object[]{
                    lista.get(i).getId(),
                    lista.get(i).getCod(),
                    lista.get(i).getStatus(),
                    lista.get(i).getNome(),
                    lista.get(i).getDescricao(),
                    lista.get(i).getQtd_estoque(),
                    lista.get(i).getEstoque_minimo(),
                    lista.get(i).getEstoque_maximo(),
                    lista.get(i).getPreco_compra(),
                    lista.get(i).getPreco_venda(),
                    lista.get(i).getBar_code(),
                    lista.get(i).getNcm(),
                    lista.get(i).getFator(),
                    lista.get(i).getData_cadastro(),
                    lista.get(i).getImagem()
                        
                
                });
            
            }
            
        } 
        catch (Exception erro) {
            
            JOptionPane.showMessageDialog(null,"Algo deu Errado na VIEW"+erro);
        }
    
    }
    
    public void carregarCampos(){
        int set = tbproduto.getSelectedRow();
        
        id = (int) tbproduto.getModel().getValueAt(set, 0);
        txtcodigo.setText(tbproduto.getModel().getValueAt(set, 1).toString());
        //txtstatus.setText(tbproduto.getModel().getValueAt(set, 2).toString());
        cbopcao.setSelectedItem(tbproduto.getModel().getValueAt(set, 2).toString());
        txtnome.setText(tbproduto.getModel().getValueAt(set, 3).toString());
        txtdescricao.setText(tbproduto.getModel().getValueAt(set, 4).toString());
        txtestoque.setText(tbproduto.getModel().getValueAt(set, 5).toString());
        txtestoqueMin.setText(tbproduto.getModel().getValueAt(set, 6).toString());
        txtestoqueMax.setText(tbproduto.getModel().getValueAt(set, 7).toString());
        txtprecoCompra.setText(tbproduto.getModel().getValueAt(set, 8).toString());
        txtprecoVenda.setText(tbproduto.getModel().getValueAt(set, 9).toString());
        txtcodigoBarra.setText(tbproduto.getModel().getValueAt(set, 10).toString());
        txtncm.setText(tbproduto.getModel().getValueAt(set, 11).toString());
        txtlucro.setText(tbproduto.getModel().getValueAt(set, 12).toString());
        txtdata.setText(tbproduto.getModel().getValueAt(set, 13).toString());
        txtimagem.setText(tbproduto.getModel().getValueAt(set, 14).toString());
                                
    }
    
}
